- docs/module-webgl-utils.html
- webgl/lessons/webgl-shaders-and-glsl.html
- webgl/lessons/webgl-shaders-and-glsl.md
- webgl/resources/webgl-utils.js
> Typo: fucntion -> function

- webgl/lessons/pl/index.html
- webgl/lessons/pl/toc.html
- webgl/lessons/pl/webgl-2d-vs-3d-library.html
- webgl/lessons/pl/webgl-2d-vs-3d-library.md
- webgl/lessons/pl/webgl-fundamentals.html
- webgl/lessons/pl/webgl-fundamentals.md
I hope the polish translation of webgl-2d-vs-3d-library is ready.
> Polish translation of webgl-2d-vs-3d-library

- webgl/lessons/pl/webgl-2d-translation.html
- webgl/lessons/pl/webgl-2d-translation.md
Hello,
i've just added a new polish translation of "webgl-2d-translation" article.
I hope it's ready to pull.
I've published it https://vinci.org.pl/ref/podstawy-webgl/przesuniecia-dwuwymiarowe-w-webgl
Kind regrads,
> Added polish translation of "webgl-2d-translation" article

- webgl/lessons/webgl-anti-patterns.md
Thanks for these great lessons! Found a typo and thought I'd send a PR as a thank you.
The word `adding` appears to be duplicated.
> Duplicate word `adding` in `webgl-anti-patterns.md`

- webgl/lessons/webgl-2-textures.md
- webgl/lessons/webgl-2d-matrices.md
- webgl/lessons/webgl-2d-rotation.md
- webgl/lessons/webgl-2d-scale.md
- webgl/lessons/webgl-2d-translation.md
- webgl/lessons/webgl-2d-vs-3d-library.md
- webgl/lessons/webgl-3d-camera.md
- webgl/lessons/webgl-3d-orthographic.md
- webgl/lessons/webgl-3d-perspective.md
- webgl/lessons/webgl-3d-textures.md
- webgl/lessons/webgl-and-alpha.md
- webgl/lessons/webgl-animation.md
- webgl/lessons/webgl-anti-patterns.md
- webgl/lessons/webgl-boilerplate.md
- webgl/lessons/webgl-drawing-multiple-things.md
- webgl/lessons/webgl-how-it-works.md
- webgl/lessons/webgl-image-processing-continued.md
- webgl/lessons/webgl-image-processing.md
- webgl/lessons/webgl-less-code-more-fun.md
- webgl/lessons/webgl-resizing-the-canvas.md
- webgl/lessons/webgl-scene-graph.md
- webgl/lessons/webgl-shaders-and-glsl.md
- webgl/lessons/webgl-text-canvas2d.md
- webgl/lessons/webgl-text-glyphs.md
- webgl/lessons/webgl-text-html.md
- webgl/lessons/webgl-text-texture.md
I'd like to offer some proofreading edits that stood out to me while reading through this great set of articles. This should correct various typos, misspellings, noun-verb plurality agreement, missing words, some style consistency, etc. Hopefully none of the edits are counter to your literary intentions.
> Various proofreading edits

- webgl/lessons/webgl-3d-textures.md
I think this is a mistake but I could be wrong.
> Correct function call

- webgl/lessons/webgl-3d-textures.md
I just changed this to show the final argument so it's clearer.
> Made function implementation a bit clearer.

- webgl/lessons/ru/toc.html
- webgl/lessons/ru/webgl-2d-drawimage.md
Just one article so far, the end of the year brings much work to do. And now holidays are waiting :).
> DrawImage translated to Russian

- webgl/lessons/zh_cn/index.md
- webgl/lessons/zh_cn/langinfo.hanson
- webgl/lessons/zh_cn/toc.html
I am working on the Simpilfy-Chinese version now, and this is just a set up, soon or latter will come with each article. 
Other things, I have no idea which branch should I push on, and I find someone direct push on the master,  so do I. if it's not right, please let me know and I will change it in time.
BTW, really good articles, helpful for me! Thanks!
> Set up the Simplify-Chinese version

- webgl/lessons/webgl-fundamentals.md
> Fix typo #98

- webgl/lessons/webgl-3d-lighting-directional.md
- webgl/lessons/zh_cn/toc.html
- webgl/lessons/zh_cn/webgl-3d-lighting-directional.md
I found this article explain [Why use inverse transpose matrix to normal](https://paroj.github.io/gltut/Illumination/Tut09%20Normal%20Transformation.html), helpful to me.
Maybe you want to take a look.:new_moon_with_face:
> Translate 'webgl-2d-lighting-directional.md'

- webgl/lessons/zh_cn/toc.html
- webgl/lessons/zh_cn/webgl-anti-patterns.md
Update is great, make interact with demo more easily.
BTW, Have you ever considered update npm to `npm@5.0.0`, and add a `package-lock.json` file.
And my translation is done by now : )
> Translate 'webgl-anti-patterns.md'

- webgl/lessons/ja/webgl-setup-and-installation.md
- webgl/lessons/webgl-setup-and-installation.md
Updated Japanese version "webgl-setup-and-install.md"
to follow the change of the English version.
> updated jp ver. "setup-and-install".

- webgl/lessons/webgl-fundamentals.md
Great website! Just fixing some typos I stumbled upon.
> Fix typos in docs

- webgl/lessons/webgl-2d-matrix-stack.md
At the end of the page, there were two typos.
> Corrected two typos

- webgl/lessons/zh_cn/webgl-3d-lighting-directional.md
hey guys, i have updated the chinese translation of the reason why not  just use 3x3 matrix instead. 
i think the old version of translation may lead to some misunderstanding.
> update chinese translate for better understanding

- docs.md
I assume that the .html files are generated?
> Fix typos and improve language

- webgl/lessons/ko/webgl-fundamentals.md
There is a missing svg.
I guess I fork early than your commit.
> [ko] missing svg link

- webgl/lessons/ko/toc.html
- webgl/lessons/ko/webgl-resizing-the-canvas.md
1. translate webgl-resizing-the-canvas
> [ko] webgl-resizing-the-canvas

- webgl/lessons/webgl-2d-rotation.md
You seem to be confused by the sentence above ;)
> metric measurement - multiply instead of divide

- webgl/lessons/ko/langinfo.hanson
- webgl/lessons/ko/toc.html
- webgl/lessons/ko/webgl-2d-rotation.md
> [ko] webgl-2d-rotation

- webgl/lessons/ko/toc.html
- webgl/lessons/ko/webgl-2d-matrices.md
I complete to translate this article.
But I'm not sure I translate it correct.
Because this article has a large amount and difficulty.
So if you know a korean translator, can you request my translation verification?
Thank you :)
> [ko] webgl-2d-matrices

- webgl/lessons/webgl-how-it-works.md
> fixed a typo in webgl-how-it-works.md

- webgl/lessons/webgl-matrix-vs-math.md
> Fix a typo

- webgl/lessons/ru/webgl-2d-drawimage.md
- webgl/lessons/webgl-2d-drawimage.md
- webgl/lessons/zh_cn/webgl-2d-drawimage.md
Looks like the `update` function should accept the interval time
> fix typo in snippet code

- webgl/lessons/webgl-3d-orthographic.md
I also had this fix in https://github.com/gfxfundamentals/webgl-fundamentals/pull/283 which was not applied. Sorry I should probably have created two pull requests.
> Fix code typo

- webgl/lessons/webgl-load-obj.md
- webgl/lessons/webgl-smallest-programs.md
- webgl/lessons/zh_cn/webgl-load-obj.md
- webgl/lessons/zh_cn/webgl-smallest-programs.md
> Translate webgl-smallest-programs.md to zh_cn

- webgl/lessons/ko/webgl-shaders-and-glsl.md
One small thing:
If I translate `header`, hash anchor(`#putting-it-all-together`) isn't worked.
Is there any solution about this?
Or do I have to leave it as it was??
> ko: update webgl-shaders-and-glsl.md

- webgl/lessons/ko/webgl-2d-matrices.md
- webgl/lessons/ko/webgl-2d-vs-3d-library.md
- webgl/lessons/ko/webgl-fundamentals.md
- webgl/lessons/webgl-2d-matrices.md
Before merge, I wanna ask a question.
This part(`where I'm coming from`) of this sentence(`I hope you at least understand where I'm coming from when I say WebGL is not a 3D library.`) means really where you're coming from?
Or it means where the WebGL is coming from? (= WebGL origin)
Please don't merge immediately, I'll reflect above question :)
> ko: webgl 2d vs 3d library

- webgl/lessons/ko/webgl-3d-orthographic.md
- webgl/lessons/ko/webgl-3d-perspective.md
Before merge, can you check this please?
-> https://twitter.com/tjy970721/status/1355075462762909697
First, I try to send a direct message, but DM is blocked.
So I leave my question as a tweet 😓
> ko: webgl 3d perspective

- webgl/resources/webgl-tutorials.css
- webgl/webgl-3d-textures-repeat-clamp.html
Currently all of label of input(radio, checkbox) cannot click.
For fixing this, I add a rule for `label`.
> fix: makes label pointable

- webgl/lessons/webgl-multiple-views.md
> fix: broken link

- webgl/lessons/ko/webgl-3d-camera.md
This is korea translation version
> ko : webgl-3d-camera

- webgl/webgl-2d-image-processing.html
> fix: make kernel list draggable

- webgl/lessons/ko/webgl-3d-lighting-directional.md
ko : webgl-3d-lighting-directional.md
> ko : webgl-3d-lighting-directional.md

- webgl/lessons/webgl-environment-maps.md
Fix minor grammar error in second paragraph.
> Fix minor grammar error in second paragraph

- webgl/webgl-2d-geometry-rotation.html
Just updated a small typo in one of the comments.
> Small typo fix in the comments.

- webgl/lessons/ja/webgl-points-lines-triangles.md
> add japanese "webgl-points-lines-triangles" page

- webgl/lessons/webgl-points-lines-triangles.md
> [tiny] Fix minor typo

- webgl/lessons/zh_cn/langinfo.hanson
- webgl/lessons/zh_cn/webgl-drawing-without-data.md
- webgl/lessons/zh_cn/webgl-picking.md
update langinfo
add webgl-drawing-without-data
add webgl-picking
> add  zh-cn translation:

- webgl/lessons/fr/webgl-drawing-multiple-things.md
> Translate "draw multiple things" to FR

- README.md
- webgl/lessons/webgl-2d-rotation.md
fix conversion from `mm` to `cm` and from `mm` to `m`
> fix conversion

- README.md
- webgl/lessons/webgl-2d-rotation.md
replace **multiply** by **divide** for consistency
> Enhancement

- webgl/lessons/zh_cn/webgl-3d-perspective.md
Corrected language issues in the Chinese translation of the file `webgl-3d-perspective.md`.
> fix: correct Chinese translation
